//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34014.
// 
#pragma warning disable 1591

namespace ProyectosWeb.SICTWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="testSoap", Namespace="http://tempuri.org/")]
    public partial class test : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getUsuarioLogeadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSistemasModulosRelacionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getModuloTareaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public test() {
            this.Url = global::ProyectosWeb.Properties.Settings.Default.ProyectosWeb_SICTWS_test;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getUsuarioLogeadoCompletedEventHandler getUsuarioLogeadoCompleted;
        
        /// <remarks/>
        public event getSistemasModulosRelacionesCompletedEventHandler getSistemasModulosRelacionesCompleted;
        
        /// <remarks/>
        public event getModuloTareaCompletedEventHandler getModuloTareaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getUsuarioLogeado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UsuarioLogin getUsuarioLogeado(string username, int idSistema) {
            object[] results = this.Invoke("getUsuarioLogeado", new object[] {
                        username,
                        idSistema});
            return ((UsuarioLogin)(results[0]));
        }
        
        /// <remarks/>
        public void getUsuarioLogeadoAsync(string username, int idSistema) {
            this.getUsuarioLogeadoAsync(username, idSistema, null);
        }
        
        /// <remarks/>
        public void getUsuarioLogeadoAsync(string username, int idSistema, object userState) {
            if ((this.getUsuarioLogeadoOperationCompleted == null)) {
                this.getUsuarioLogeadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUsuarioLogeadoOperationCompleted);
            }
            this.InvokeAsync("getUsuarioLogeado", new object[] {
                        username,
                        idSistema}, this.getUsuarioLogeadoOperationCompleted, userState);
        }
        
        private void OngetUsuarioLogeadoOperationCompleted(object arg) {
            if ((this.getUsuarioLogeadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUsuarioLogeadoCompleted(this, new getUsuarioLogeadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getSistemasModulosRelaciones", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SistemasModulos getSistemasModulosRelaciones(int idSistema, int idUsuario, PerfilLogin[] perfiles) {
            object[] results = this.Invoke("getSistemasModulosRelaciones", new object[] {
                        idSistema,
                        idUsuario,
                        perfiles});
            return ((SistemasModulos)(results[0]));
        }
        
        /// <remarks/>
        public void getSistemasModulosRelacionesAsync(int idSistema, int idUsuario, PerfilLogin[] perfiles) {
            this.getSistemasModulosRelacionesAsync(idSistema, idUsuario, perfiles, null);
        }
        
        /// <remarks/>
        public void getSistemasModulosRelacionesAsync(int idSistema, int idUsuario, PerfilLogin[] perfiles, object userState) {
            if ((this.getSistemasModulosRelacionesOperationCompleted == null)) {
                this.getSistemasModulosRelacionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSistemasModulosRelacionesOperationCompleted);
            }
            this.InvokeAsync("getSistemasModulosRelaciones", new object[] {
                        idSistema,
                        idUsuario,
                        perfiles}, this.getSistemasModulosRelacionesOperationCompleted, userState);
        }
        
        private void OngetSistemasModulosRelacionesOperationCompleted(object arg) {
            if ((this.getSistemasModulosRelacionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSistemasModulosRelacionesCompleted(this, new getSistemasModulosRelacionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getModuloTarea", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable getModuloTarea(ModuloTarea tarea, string opcionTarea, int idUsuario, int idSistema) {
            object[] results = this.Invoke("getModuloTarea", new object[] {
                        tarea,
                        opcionTarea,
                        idUsuario,
                        idSistema});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void getModuloTareaAsync(ModuloTarea tarea, string opcionTarea, int idUsuario, int idSistema) {
            this.getModuloTareaAsync(tarea, opcionTarea, idUsuario, idSistema, null);
        }
        
        /// <remarks/>
        public void getModuloTareaAsync(ModuloTarea tarea, string opcionTarea, int idUsuario, int idSistema, object userState) {
            if ((this.getModuloTareaOperationCompleted == null)) {
                this.getModuloTareaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetModuloTareaOperationCompleted);
            }
            this.InvokeAsync("getModuloTarea", new object[] {
                        tarea,
                        opcionTarea,
                        idUsuario,
                        idSistema}, this.getModuloTareaOperationCompleted, userState);
        }
        
        private void OngetModuloTareaOperationCompleted(object arg) {
            if ((this.getModuloTareaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getModuloTareaCompleted(this, new getModuloTareaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UsuarioLogin {
        
        private int idUsuarioField;
        
        private int idCatalogoProveedoresField;
        
        private string nombreField;
        
        private string esEmpleadoField;
        
        private string contraseñaField;
        
        private string estadoField;
        
        private PersonaLogin personaField;
        
        private System.DateTime tiempoExpiracionField;
        
        private int linkClikedField;
        
        private PerfilLogin[] perfilesField;
        
        private GrupoLogin[] gruposField;
        
        private SistemasModulos sistemasModulosField;
        
        /// <comentarios/>
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <comentarios/>
        public int idCatalogoProveedores {
            get {
                return this.idCatalogoProveedoresField;
            }
            set {
                this.idCatalogoProveedoresField = value;
            }
        }
        
        /// <comentarios/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string esEmpleado {
            get {
                return this.esEmpleadoField;
            }
            set {
                this.esEmpleadoField = value;
            }
        }
        
        /// <comentarios/>
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
            }
        }
        
        /// <comentarios/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        public PersonaLogin persona {
            get {
                return this.personaField;
            }
            set {
                this.personaField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime tiempoExpiracion {
            get {
                return this.tiempoExpiracionField;
            }
            set {
                this.tiempoExpiracionField = value;
            }
        }
        
        /// <comentarios/>
        public int linkCliked {
            get {
                return this.linkClikedField;
            }
            set {
                this.linkClikedField = value;
            }
        }
        
        /// <comentarios/>
        public PerfilLogin[] Perfiles {
            get {
                return this.perfilesField;
            }
            set {
                this.perfilesField = value;
            }
        }
        
        /// <comentarios/>
        public GrupoLogin[] Grupos {
            get {
                return this.gruposField;
            }
            set {
                this.gruposField = value;
            }
        }
        
        /// <comentarios/>
        public SistemasModulos sistemasModulos {
            get {
                return this.sistemasModulosField;
            }
            set {
                this.sistemasModulosField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonaLogin {
        
        private int idPersonaField;
        
        private int idUsuarioField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private System.DateTime fechaRegistroField;
        
        private string tecnologiasField;
        
        private string estadoField;
        
        private string emailField;
        
        private long telefonoField;
        
        private string empresaField;
        
        /// <comentarios/>
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
            }
        }
        
        /// <comentarios/>
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
            }
        }
        
        /// <comentarios/>
        public string tecnologias {
            get {
                return this.tecnologiasField;
            }
            set {
                this.tecnologiasField = value;
            }
        }
        
        /// <comentarios/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <comentarios/>
        public long telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <comentarios/>
        public string empresa {
            get {
                return this.empresaField;
            }
            set {
                this.empresaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TimeSpan {
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ModuloTarea {
        
        private int idField;
        
        private string claveField;
        
        private string nombreField;
        
        private string descripcionField;
        
        private string referenciaField;
        
        private string estadoField;
        
        private string fechaInicioField;
        
        private string fechaFinEstimadaField;
        
        private string fechaFinRealField;
        
        private string diferenciaFechaFinField;
        
        private TimeSpan horaEstimadaField;
        
        private TimeSpan horaRealField;
        
        private TimeSpan diferenciaHoraFinField;
        
        /// <comentarios/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public string clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
            }
        }
        
        /// <comentarios/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
            }
        }
        
        /// <comentarios/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        public string FechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
            }
        }
        
        /// <comentarios/>
        public string FechaFinEstimada {
            get {
                return this.fechaFinEstimadaField;
            }
            set {
                this.fechaFinEstimadaField = value;
            }
        }
        
        /// <comentarios/>
        public string FechaFinReal {
            get {
                return this.fechaFinRealField;
            }
            set {
                this.fechaFinRealField = value;
            }
        }
        
        /// <comentarios/>
        public string DiferenciaFechaFin {
            get {
                return this.diferenciaFechaFinField;
            }
            set {
                this.diferenciaFechaFinField = value;
            }
        }
        
        /// <comentarios/>
        public TimeSpan horaEstimada {
            get {
                return this.horaEstimadaField;
            }
            set {
                this.horaEstimadaField = value;
            }
        }
        
        /// <comentarios/>
        public TimeSpan horaReal {
            get {
                return this.horaRealField;
            }
            set {
                this.horaRealField = value;
            }
        }
        
        /// <comentarios/>
        public TimeSpan DiferenciaHoraFin {
            get {
                return this.diferenciaHoraFinField;
            }
            set {
                this.diferenciaHoraFinField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UsuariosOpciones {
        
        private int idUsuarioOpcionField;
        
        private int idUsuarioField;
        
        private int idOpcionField;
        
        private string visibleField;
        
        private Opcion opcionField;
        
        /// <comentarios/>
        public int idUsuarioOpcion {
            get {
                return this.idUsuarioOpcionField;
            }
            set {
                this.idUsuarioOpcionField = value;
            }
        }
        
        /// <comentarios/>
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <comentarios/>
        public int idOpcion {
            get {
                return this.idOpcionField;
            }
            set {
                this.idOpcionField = value;
            }
        }
        
        /// <comentarios/>
        public string visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
        
        /// <comentarios/>
        public Opcion opcion {
            get {
                return this.opcionField;
            }
            set {
                this.opcionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Opcion {
        
        private int idOpcionField;
        
        private int idPantallaField;
        
        private string nombreField;
        
        private string descripcionField;
        
        private string idAspField;
        
        private string componenteIndexField;
        
        private int chkboxTreeindexField;
        
        private string idcheckboxField;
        
        private int estadoField;
        
        private Pantalla pantallaField;
        
        /// <comentarios/>
        public int idOpcion {
            get {
                return this.idOpcionField;
            }
            set {
                this.idOpcionField = value;
            }
        }
        
        /// <comentarios/>
        public int idPantalla {
            get {
                return this.idPantallaField;
            }
            set {
                this.idPantallaField = value;
            }
        }
        
        /// <comentarios/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        public string idAsp {
            get {
                return this.idAspField;
            }
            set {
                this.idAspField = value;
            }
        }
        
        /// <comentarios/>
        public string componenteIndex {
            get {
                return this.componenteIndexField;
            }
            set {
                this.componenteIndexField = value;
            }
        }
        
        /// <comentarios/>
        public int chkboxTreeindex {
            get {
                return this.chkboxTreeindexField;
            }
            set {
                this.chkboxTreeindexField = value;
            }
        }
        
        /// <comentarios/>
        public string idcheckbox {
            get {
                return this.idcheckboxField;
            }
            set {
                this.idcheckboxField = value;
            }
        }
        
        /// <comentarios/>
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        public Pantalla pantalla {
            get {
                return this.pantallaField;
            }
            set {
                this.pantallaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Pantalla {
        
        private int idPantallaField;
        
        private int idModuloField;
        
        private string nombreField;
        
        private string descripcionField;
        
        private string idAspField;
        
        private int estadoField;
        
        private int pantallaIndexField;
        
        /// <comentarios/>
        public int idPantalla {
            get {
                return this.idPantallaField;
            }
            set {
                this.idPantallaField = value;
            }
        }
        
        /// <comentarios/>
        public int idModulo {
            get {
                return this.idModuloField;
            }
            set {
                this.idModuloField = value;
            }
        }
        
        /// <comentarios/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        public string idAsp {
            get {
                return this.idAspField;
            }
            set {
                this.idAspField = value;
            }
        }
        
        /// <comentarios/>
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        public int pantallaIndex {
            get {
                return this.pantallaIndexField;
            }
            set {
                this.pantallaIndexField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UsuariosPantallas {
        
        private int idUsuarioPantallaField;
        
        private int idPantallaField;
        
        private int idUsuarioField;
        
        private string visibleField;
        
        private string componenteIndexField;
        
        private Pantalla pantallaField;
        
        /// <comentarios/>
        public int idUsuarioPantalla {
            get {
                return this.idUsuarioPantallaField;
            }
            set {
                this.idUsuarioPantallaField = value;
            }
        }
        
        /// <comentarios/>
        public int idPantalla {
            get {
                return this.idPantallaField;
            }
            set {
                this.idPantallaField = value;
            }
        }
        
        /// <comentarios/>
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
        
        /// <comentarios/>
        public string componenteIndex {
            get {
                return this.componenteIndexField;
            }
            set {
                this.componenteIndexField = value;
            }
        }
        
        /// <comentarios/>
        public Pantalla pantalla {
            get {
                return this.pantallaField;
            }
            set {
                this.pantallaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UsuariosModulos {
        
        private int idUsuarioModuloField;
        
        private int idModuloField;
        
        private int idUsuarioField;
        
        private string h3VisibleField;
        
        private string divVisibleField;
        
        private Modulo moduloField;
        
        /// <comentarios/>
        public int idUsuarioModulo {
            get {
                return this.idUsuarioModuloField;
            }
            set {
                this.idUsuarioModuloField = value;
            }
        }
        
        /// <comentarios/>
        public int idModulo {
            get {
                return this.idModuloField;
            }
            set {
                this.idModuloField = value;
            }
        }
        
        /// <comentarios/>
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string h3Visible {
            get {
                return this.h3VisibleField;
            }
            set {
                this.h3VisibleField = value;
            }
        }
        
        /// <comentarios/>
        public string divVisible {
            get {
                return this.divVisibleField;
            }
            set {
                this.divVisibleField = value;
            }
        }
        
        /// <comentarios/>
        public Modulo modulo {
            get {
                return this.moduloField;
            }
            set {
                this.moduloField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Modulo {
        
        private int idModuloField;
        
        private string nombreField;
        
        private string descripcionField;
        
        private string h3IdField;
        
        private string divIdField;
        
        private int estadoField;
        
        /// <comentarios/>
        public int idModulo {
            get {
                return this.idModuloField;
            }
            set {
                this.idModuloField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        public string h3Id {
            get {
                return this.h3IdField;
            }
            set {
                this.h3IdField = value;
            }
        }
        
        /// <comentarios/>
        public string divId {
            get {
                return this.divIdField;
            }
            set {
                this.divIdField = value;
            }
        }
        
        /// <comentarios/>
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PerfilesOpciones {
        
        private int idPerfilOpcionField;
        
        private int idPerfilField;
        
        private int idOpcionField;
        
        private string visibleField;
        
        private Opcion opcionField;
        
        /// <comentarios/>
        public int idPerfilOpcion {
            get {
                return this.idPerfilOpcionField;
            }
            set {
                this.idPerfilOpcionField = value;
            }
        }
        
        /// <comentarios/>
        public int idPerfil {
            get {
                return this.idPerfilField;
            }
            set {
                this.idPerfilField = value;
            }
        }
        
        /// <comentarios/>
        public int idOpcion {
            get {
                return this.idOpcionField;
            }
            set {
                this.idOpcionField = value;
            }
        }
        
        /// <comentarios/>
        public string visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
        
        /// <comentarios/>
        public Opcion opcion {
            get {
                return this.opcionField;
            }
            set {
                this.opcionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PerfilesPantallas {
        
        private int idPerfilPantallaField;
        
        private int idPantallaField;
        
        private int idPerfilField;
        
        private string visibleField;
        
        private string componenteIndexField;
        
        private Pantalla pantallaField;
        
        /// <comentarios/>
        public int idPerfilPantalla {
            get {
                return this.idPerfilPantallaField;
            }
            set {
                this.idPerfilPantallaField = value;
            }
        }
        
        /// <comentarios/>
        public int idPantalla {
            get {
                return this.idPantallaField;
            }
            set {
                this.idPantallaField = value;
            }
        }
        
        /// <comentarios/>
        public int idPerfil {
            get {
                return this.idPerfilField;
            }
            set {
                this.idPerfilField = value;
            }
        }
        
        /// <comentarios/>
        public string visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
        
        /// <comentarios/>
        public string componenteIndex {
            get {
                return this.componenteIndexField;
            }
            set {
                this.componenteIndexField = value;
            }
        }
        
        /// <comentarios/>
        public Pantalla pantalla {
            get {
                return this.pantallaField;
            }
            set {
                this.pantallaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PerfilesModulos {
        
        private int idPerfilModuloField;
        
        private int idModuloField;
        
        private int idPerfilField;
        
        private string h3VisibleField;
        
        private string divVisibleField;
        
        private Modulo moduloField;
        
        /// <comentarios/>
        public int idPerfilModulo {
            get {
                return this.idPerfilModuloField;
            }
            set {
                this.idPerfilModuloField = value;
            }
        }
        
        /// <comentarios/>
        public int idModulo {
            get {
                return this.idModuloField;
            }
            set {
                this.idModuloField = value;
            }
        }
        
        /// <comentarios/>
        public int idPerfil {
            get {
                return this.idPerfilField;
            }
            set {
                this.idPerfilField = value;
            }
        }
        
        /// <comentarios/>
        public string h3Visible {
            get {
                return this.h3VisibleField;
            }
            set {
                this.h3VisibleField = value;
            }
        }
        
        /// <comentarios/>
        public string divVisible {
            get {
                return this.divVisibleField;
            }
            set {
                this.divVisibleField = value;
            }
        }
        
        /// <comentarios/>
        public Modulo modulo {
            get {
                return this.moduloField;
            }
            set {
                this.moduloField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SistemasModulos {
        
        private int idSistemaModuloField;
        
        private int idModuloField;
        
        private int idSistemaField;
        
        private string h3visibleField;
        
        private string divvisibleField;
        
        private Modulo moduloField;
        
        private SistemasModulos[] sistemasModulosField;
        
        private PerfilesModulos[] perfilesModulosField;
        
        private PerfilesPantallas[] perfilesPantallasField;
        
        private PerfilesOpciones[] perfilesOpcionesField;
        
        private UsuariosModulos[] usuariosModulosField;
        
        private UsuariosPantallas[] usuariosPantallasField;
        
        private UsuariosOpciones[] usuariosOpcionesField;
        
        /// <comentarios/>
        public int idSistemaModulo {
            get {
                return this.idSistemaModuloField;
            }
            set {
                this.idSistemaModuloField = value;
            }
        }
        
        /// <comentarios/>
        public int idModulo {
            get {
                return this.idModuloField;
            }
            set {
                this.idModuloField = value;
            }
        }
        
        /// <comentarios/>
        public int idSistema {
            get {
                return this.idSistemaField;
            }
            set {
                this.idSistemaField = value;
            }
        }
        
        /// <comentarios/>
        public string h3visible {
            get {
                return this.h3visibleField;
            }
            set {
                this.h3visibleField = value;
            }
        }
        
        /// <comentarios/>
        public string divvisible {
            get {
                return this.divvisibleField;
            }
            set {
                this.divvisibleField = value;
            }
        }
        
        /// <comentarios/>
        public Modulo modulo {
            get {
                return this.moduloField;
            }
            set {
                this.moduloField = value;
            }
        }
        
        /// <comentarios/>
        public SistemasModulos[] sistemasModulos {
            get {
                return this.sistemasModulosField;
            }
            set {
                this.sistemasModulosField = value;
            }
        }
        
        /// <comentarios/>
        public PerfilesModulos[] perfilesModulos {
            get {
                return this.perfilesModulosField;
            }
            set {
                this.perfilesModulosField = value;
            }
        }
        
        /// <comentarios/>
        public PerfilesPantallas[] perfilesPantallas {
            get {
                return this.perfilesPantallasField;
            }
            set {
                this.perfilesPantallasField = value;
            }
        }
        
        /// <comentarios/>
        public PerfilesOpciones[] perfilesOpciones {
            get {
                return this.perfilesOpcionesField;
            }
            set {
                this.perfilesOpcionesField = value;
            }
        }
        
        /// <comentarios/>
        public UsuariosModulos[] usuariosModulos {
            get {
                return this.usuariosModulosField;
            }
            set {
                this.usuariosModulosField = value;
            }
        }
        
        /// <comentarios/>
        public UsuariosPantallas[] usuariosPantallas {
            get {
                return this.usuariosPantallasField;
            }
            set {
                this.usuariosPantallasField = value;
            }
        }
        
        /// <comentarios/>
        public UsuariosOpciones[] usuariosOpciones {
            get {
                return this.usuariosOpcionesField;
            }
            set {
                this.usuariosOpcionesField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GrupoLogin {
        
        private int idGrupoField;
        
        private int idUsuarioField;
        
        private string nombreField;
        
        private string descripcionField;
        
        private string estadoField;
        
        /// <comentarios/>
        public int idGrupo {
            get {
                return this.idGrupoField;
            }
            set {
                this.idGrupoField = value;
            }
        }
        
        /// <comentarios/>
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PerfilLogin {
        
        private int idPerfilField;
        
        private int idGrupoField;
        
        private int idCatalogoPerfilField;
        
        private string nombreField;
        
        private string descripcionField;
        
        private string usuarioAltaField;
        
        private string usuarioBajaField;
        
        private string usuarioModificaField;
        
        private string estadoField;
        
        /// <comentarios/>
        public int idPerfil {
            get {
                return this.idPerfilField;
            }
            set {
                this.idPerfilField = value;
            }
        }
        
        /// <comentarios/>
        public int idGrupo {
            get {
                return this.idGrupoField;
            }
            set {
                this.idGrupoField = value;
            }
        }
        
        /// <comentarios/>
        public int idCatalogoPerfil {
            get {
                return this.idCatalogoPerfilField;
            }
            set {
                this.idCatalogoPerfilField = value;
            }
        }
        
        /// <comentarios/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        public string usuarioAlta {
            get {
                return this.usuarioAltaField;
            }
            set {
                this.usuarioAltaField = value;
            }
        }
        
        /// <comentarios/>
        public string usuarioBaja {
            get {
                return this.usuarioBajaField;
            }
            set {
                this.usuarioBajaField = value;
            }
        }
        
        /// <comentarios/>
        public string usuarioModifica {
            get {
                return this.usuarioModificaField;
            }
            set {
                this.usuarioModificaField = value;
            }
        }
        
        /// <comentarios/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getUsuarioLogeadoCompletedEventHandler(object sender, getUsuarioLogeadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUsuarioLogeadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUsuarioLogeadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsuarioLogin Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsuarioLogin)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getSistemasModulosRelacionesCompletedEventHandler(object sender, getSistemasModulosRelacionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSistemasModulosRelacionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSistemasModulosRelacionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SistemasModulos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SistemasModulos)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getModuloTareaCompletedEventHandler(object sender, getModuloTareaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getModuloTareaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getModuloTareaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591